"""PHASE-15 15G — pip-tools lockfile sync guard.

Cheap permanent check that the ``.in`` → ``pip-compile`` → ``.txt`` pairs (F7) do not drift:
every top-level declaration in a ``.in`` resolves to a ``==`` pin in its compiled ``.txt``.
Catches someone hand-adding a dep to ``.in`` without recompiling.
"""

import re
from pathlib import Path

import pytest

REQ_DIR = Path(__file__).resolve().parents[1]  # bmo/pi/
# pip-compile omits these "unsafe" packages unless --allow-unsafe.
UNSAFE = {"pip", "setuptools", "wheel", "distribute"}

PAIRS = [
    ("requirements.in", "requirements.txt"),
    ("requirements-ci.in", "requirements-ci.txt"),
    ("requirements-test.in", "requirements-test.txt"),
]


def _norm(name: str) -> str:  # PEP 503 normalization
    return re.sub(r"[-_.]+", "-", name).lower()


def _declared(in_path: Path) -> set[str]:
    names = set()
    for line in in_path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if not line or line.startswith(("-", "--")):
            continue
        name = re.split(r"[<>=!~\[; ]", line, 1)[0]
        if name:
            names.add(_norm(name))
    return names


def _pinned(txt_path: Path) -> set[str]:
    text = txt_path.read_text(encoding="utf-8")
    return {_norm(m.group(1)) for m in re.finditer(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==", text, re.M)}


@pytest.mark.parametrize("in_name,txt_name", PAIRS)
def test_declared_deps_are_pinned(in_name, txt_name):
    in_path, txt_path = REQ_DIR / in_name, REQ_DIR / txt_name
    assert in_path.exists() and txt_path.exists()
    missing = (_declared(in_path) - UNSAFE) - _pinned(txt_path)
    assert not missing, (
        f"{in_name} declares {sorted(missing)} with no pin in {txt_name}. "
        f"Recompile: pip-compile --extra-index-url https://download.pytorch.org/whl/cpu "
        f"-o {txt_name} {in_name}"
    )


def test_main_lockfile_is_compiled():
    head = (REQ_DIR / "requirements.txt").read_text(encoding="utf-8")[:400]
    assert "autogenerated by pip-compile" in head
