monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-107c701400.hdmi"
      }
    ]
    actions = {
      update-props = {
        device.profile = "hdmi-stereo"
      }
    }
  }
]
